language: node_js
node_js:
  - '10'

script:
  - yarn bundle
  - mv static_assets build/static_assets

deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
